"""update llm_call_log table

Revision ID: 39944a9db8ea
Revises: 20260429_000007
Create Date: 2026-04-30 17:52:03.046625
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '39944a9db8ea'
down_revision = '20260429_000007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_call_log', sa.Column('run_id', sa.String(length=100), nullable=True))
    op.add_column('llm_call_log', sa.Column('parent_run_id', sa.String(length=100), nullable=True))
    op.add_column('llm_call_log', sa.Column('trace_id', sa.String(length=100), nullable=True))
    op.add_column('llm_call_log', sa.Column('run_type', sa.String(length=30), nullable=True))
    op.add_column('llm_call_log', sa.Column('execution_order', sa.Integer(), nullable=True))
    op.add_column('llm_call_log', sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('llm_call_log', sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('llm_call_log', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('llm_call_log', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.alter_column('llm_call_log', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_call_log', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_call_log', 'total_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_call_log', 'estimated_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_call_log', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_call_log', 'call_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_call_log', 'call_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'success'::character varying"),
               existing_nullable=False)
    op.alter_column('llm_call_log', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=False)
    op.alter_column('llm_call_log', 'estimated_cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('llm_call_log', 'total_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('llm_call_log', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('llm_call_log', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('llm_call_log', 'ended_at')
    op.drop_column('llm_call_log', 'started_at')
    op.drop_column('llm_call_log', 'output_json')
    op.drop_column('llm_call_log', 'request_json')
    op.drop_column('llm_call_log', 'execution_order')
    op.drop_column('llm_call_log', 'run_type')
    op.drop_column('llm_call_log', 'trace_id')
    op.drop_column('llm_call_log', 'parent_run_id')
    op.drop_column('llm_call_log', 'run_id')
    op.create_table('admin_menu',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('menu_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('menu_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('menu_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('depth', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('sort_no', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_menu.id'], name=op.f('fk_adm_menu_parent')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_menu_pkey'))
    )
    op.create_index(op.f('uq_admin_menu_key'), 'admin_menu', ['menu_key'], unique=True, postgresql_where="(del_tf = 'N'::bpchar)")
    op.create_table('admin_group',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('group_desc', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_group_pkey'))
    )
    op.create_index(op.f('uq_admin_group_name'), 'admin_group', ['group_name'], unique=True, postgresql_where="(del_tf = 'N'::bpchar)")
    op.create_table('admin_access_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action_target', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('result_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_admin_access_log_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_access_log_pkey'))
    )
    op.create_index(op.f('idx_admin_access_log_created_at'), 'admin_access_log', ['created_at'], unique=False)
    op.create_index(op.f('idx_admin_access_log_admin_id'), 'admin_access_log', ['admin_id'], unique=False)
    op.create_table('admin',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('login_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], name=op.f('fk_admin_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_pkey'))
    )
    op.create_index(op.f('uq_admin_login_id'), 'admin', ['login_id'], unique=True, postgresql_where="(del_tf = 'N'::bpchar)")
    op.create_table('admin_group_menu',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('menu_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('read_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('write_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('delete_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], name=op.f('fk_admin_group_menu_group')),
    sa.ForeignKeyConstraint(['menu_id'], ['admin_menu.id'], name=op.f('fk_admin_group_menu_menu')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_group_menu_pkey'))
    )
    op.create_index(op.f('uq_admin_group_menu'), 'admin_group_menu', ['group_id', 'menu_id'], unique=True, postgresql_where="(del_tf = 'N'::bpchar)")
    op.create_table('admin_refresh_token',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revoked_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.VARCHAR(length=1), server_default=sa.text("'Y'::character varying"), autoincrement=False, nullable=True),
    sa.Column('del_tf', sa.VARCHAR(length=1), server_default=sa.text("'N'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_admin_refresh_token_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_refresh_token_pkey'))
    )
    op.create_index(op.f('idx_admin_refresh_token_expires_at'), 'admin_refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('idx_admin_refresh_token_admin_id'), 'admin_refresh_token', ['admin_id'], unique=False)
    # ### end Alembic commands ###
