"""feat add column JobPostingAnalysisReport

Revision ID: 63349b0a806d
Revises: fe770c75c489
Create Date: 2026-05-12 16:08:46.627132
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '63349b0a806d'
down_revision = 'fe770c75c489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posting', sa.Column('posting_text_hash', sa.String(length=64), nullable=False))
    op.add_column('job_posting_analysis_report', sa.Column('risk_level', sa.String(length=30), nullable=True))
    op.add_column('job_posting_analysis_report', sa.Column('issue_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_posting_analysis_report', sa.Column('violation_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_posting_analysis_report', sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_posting_analysis_report', sa.Column('confidence_score', sa.Integer(), nullable=True))
    op.add_column('job_posting_analysis_report', sa.Column('detected_issue_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_posting_analysis_report', sa.Column('retrieval_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_posting_analysis_report', sa.Column('prompt_version', sa.String(length=50), nullable=True))
    op.add_column('job_posting_analysis_report', sa.Column('pipeline_version', sa.String(length=50), nullable=True))
    op.add_column('job_posting_analysis_report', sa.Column('summary_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posting_analysis_report', 'summary_text')
    op.drop_column('job_posting_analysis_report', 'pipeline_version')
    op.drop_column('job_posting_analysis_report', 'prompt_version')
    op.drop_column('job_posting_analysis_report', 'retrieval_summary')
    op.drop_column('job_posting_analysis_report', 'detected_issue_types')
    op.drop_column('job_posting_analysis_report', 'confidence_score')
    op.drop_column('job_posting_analysis_report', 'warning_count')
    op.drop_column('job_posting_analysis_report', 'violation_count')
    op.drop_column('job_posting_analysis_report', 'issue_count')
    op.drop_column('job_posting_analysis_report', 'risk_level')
    op.drop_column('job_posting', 'posting_text_hash')
    op.create_table('admin',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('login_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], name=op.f('fk_admin_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_pkey'))
    )
    op.create_table('admin_refresh_token',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revoked_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.VARCHAR(length=1), server_default=sa.text("'Y'::character varying"), autoincrement=False, nullable=True),
    sa.Column('del_tf', sa.VARCHAR(length=1), server_default=sa.text("'N'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_admin_refresh_token_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_refresh_token_pkey'))
    )
    op.create_table('admin_group',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('group_desc', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_group_pkey'))
    )
    op.create_table('admin_group_menu',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('menu_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('read_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('write_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('delete_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], name=op.f('fk_admin_group_menu_group')),
    sa.ForeignKeyConstraint(['menu_id'], ['admin_menu.id'], name=op.f('fk_admin_group_menu_menu')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_group_menu_pkey'))
    )
    op.create_table('admin_menu',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('menu_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('menu_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('menu_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('depth', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('sort_no', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_menu.id'], name=op.f('fk_adm_menu_parent')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_menu_pkey'))
    )
    op.create_table('admin_access_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action_target', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('result_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_admin_access_log_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_access_log_pkey'))
    )
    # ### end Alembic commands ###
