"""feat add job posting analysis tables

Revision ID: df6d7bcf9214
Revises: a1c25d08fe0e
Create Date: 2026-05-11 21:53:40.736509
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'df6d7bcf9214'
down_revision = 'a1c25d08fe0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_admin_access_log_admin_id'), table_name='admin_access_log')
    op.drop_index(op.f('idx_admin_access_log_created_at'), table_name='admin_access_log')
    op.drop_index(op.f('idx_admin_refresh_token_admin_id'), table_name='admin_refresh_token')
    op.drop_index(op.f('idx_admin_refresh_token_expires_at'), table_name='admin_refresh_token')
    op.drop_index(op.f('uq_admin_menu_key'), table_name='admin_menu', postgresql_where="(del_tf = 'N'::bpchar)")
    op.drop_index(op.f('uq_admin_group_name'), table_name='admin_group', postgresql_where="(del_tf = 'N'::bpchar)")
    op.drop_index(op.f('uq_admin_group_menu'), table_name='admin_group_menu', postgresql_where="(del_tf = 'N'::bpchar)")
    op.drop_index(op.f('uq_admin_login_id'), table_name='admin', postgresql_where="(del_tf = 'N'::bpchar)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('login_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], name=op.f('fk_admin_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_pkey'))
    )
    op.create_index(op.f('uq_admin_login_id'), 'admin', ['login_id'], unique=True, postgresql_where="(del_tf = 'N'::bpchar)")
    op.create_table('admin_group_menu',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('menu_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('read_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('write_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('delete_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], name=op.f('fk_admin_group_menu_group')),
    sa.ForeignKeyConstraint(['menu_id'], ['admin_menu.id'], name=op.f('fk_admin_group_menu_menu')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_group_menu_pkey'))
    )
    op.create_index(op.f('uq_admin_group_menu'), 'admin_group_menu', ['group_id', 'menu_id'], unique=True, postgresql_where="(del_tf = 'N'::bpchar)")
    op.create_table('admin_group',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('group_desc', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_group_pkey'))
    )
    op.create_index(op.f('uq_admin_group_name'), 'admin_group', ['group_name'], unique=True, postgresql_where="(del_tf = 'N'::bpchar)")
    op.create_table('admin_menu',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('menu_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('menu_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('menu_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('depth', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('sort_no', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_menu.id'], name=op.f('fk_adm_menu_parent')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_menu_pkey'))
    )
    op.create_index(op.f('uq_admin_menu_key'), 'admin_menu', ['menu_key'], unique=True, postgresql_where="(del_tf = 'N'::bpchar)")
    op.create_table('admin_refresh_token',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revoked_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.VARCHAR(length=1), server_default=sa.text("'Y'::character varying"), autoincrement=False, nullable=True),
    sa.Column('del_tf', sa.VARCHAR(length=1), server_default=sa.text("'N'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_admin_refresh_token_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_refresh_token_pkey'))
    )
    op.create_index(op.f('idx_admin_refresh_token_expires_at'), 'admin_refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('idx_admin_refresh_token_admin_id'), 'admin_refresh_token', ['admin_id'], unique=False)
    op.create_table('admin_access_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action_target', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('result_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_admin_access_log_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_access_log_pkey'))
    )
    op.create_index(op.f('idx_admin_access_log_created_at'), 'admin_access_log', ['created_at'], unique=False)
    op.create_index(op.f('idx_admin_access_log_admin_id'), 'admin_access_log', ['admin_id'], unique=False)
    # ### end Alembic commands ###
