"""feat add job posting analysis tables

Revision ID: df6d7bcf9214
Revises: a1c25d08fe0e
Create Date: 2026-05-11 21:53:40.736509
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'df6d7bcf9214'
down_revision = 'a1c25d08fe0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Compatibility shim.

    The original autogenerated body only touched legacy admin indexes and was
    unrelated to the job-posting analysis schema introduced in subsequent
    revisions. Keeping this revision as a no-op makes fresh migrations safer
    and avoids surprising schema drift.
    """
    return None


def downgrade() -> None:
    return None
