"""feat add job posting analysis tables

Revision ID: fe770c75c489
Revises: df6d7bcf9214
Create Date: 2026-05-11 22:07:56.548065
"""

from __future__ import annotations

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'fe770c75c489'
down_revision = 'df6d7bcf9214'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_source', sa.String(length=30), nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('external_posting_id', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('target_job', sa.String(length=100), nullable=True),
    sa.Column('career_level', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('salary_text', sa.String(length=255), nullable=True),
    sa.Column('posting_text', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('posting_status', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_posting_knowledge_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('version_label', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_ext', sa.String(length=20), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extract_status', sa.String(length=30), nullable=False),
    sa.Column('index_status', sa.String(length=30), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_posting_knowledge_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_source_id', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('chunk_key', sa.String(length=100), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('issue_code', sa.String(length=100), nullable=True),
    sa.Column('risk_category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=True),
    sa.Column('law_name', sa.String(length=255), nullable=True),
    sa.Column('article_no', sa.String(length=100), nullable=True),
    sa.Column('penalty_guide', sa.Text(), nullable=True),
    sa.Column('violation_text', sa.Text(), nullable=True),
    sa.Column('violation_reason', sa.Text(), nullable=True),
    sa.Column('correction_suggestion', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('use_tf', sa.String(length=1), nullable=False),
    sa.Column('del_tf', sa.String(length=1), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['job_posting_knowledge_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('job_posting_analysis_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('analysis_status', sa.String(length=30), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('analysis_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('parsed_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('attractiveness_score', sa.Integer(), nullable=True),
    sa.Column('issue_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('improvement_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rewrite_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_job_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ai_job_id'], ['ai_job.id'], ),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_posting.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_group',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('group_desc', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_group_pkey'))
    )
    op.create_table('admin',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('login_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], name=op.f('fk_admin_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_pkey'))
    )
    op.create_table('admin_access_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action_target', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('result_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_admin_access_log_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_access_log_pkey'))
    )
    op.create_table('admin_menu',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('menu_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('menu_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('menu_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('depth', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('sort_no', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_menu.id'], name=op.f('fk_adm_menu_parent')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_menu_pkey'))
    )
    op.create_table('admin_group_menu',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('menu_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('read_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('write_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('delete_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('use_tf', sa.CHAR(length=1), server_default=sa.text("'Y'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('del_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], name=op.f('fk_admin_group_menu_group')),
    sa.ForeignKeyConstraint(['menu_id'], ['admin_menu.id'], name=op.f('fk_admin_group_menu_menu')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_group_menu_pkey'))
    )
    op.create_table('admin_refresh_token',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revoked_tf', sa.CHAR(length=1), server_default=sa.text("'N'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reg_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('up_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('del_adm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('del_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('use_tf', sa.VARCHAR(length=1), server_default=sa.text("'Y'::character varying"), autoincrement=False, nullable=True),
    sa.Column('del_tf', sa.VARCHAR(length=1), server_default=sa.text("'N'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_admin_refresh_token_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_refresh_token_pkey'))
    )
    op.drop_table('job_posting_analysis_report')
    op.drop_table('job_posting_knowledge_chunk')
    op.drop_table('job_posting_knowledge_source')
    op.drop_table('job_posting')
    # ### end Alembic commands ###
